language: node_js
node_js:
  - 'stable'
sudo: false
env:
  - secure: "sqpbseH2+V4DHgGwQTeXGtnK7wzOu8WSaSFF6R+Y0wocE0SjS+pceHnrjTHHmPOwevCmpMasUgJcjU2CaECICrpNV+8qkkUTj9ifLs8ywQNuk/WtxBiVRbMYrZsiwrSWb65eVgzpzfl/H4F3byglMxr3p2EGO0epYvDTD44+UDviO6awSZCeY1vgAw07g2azDrEiWKgFNenqOBWPxhOQe1/FhThJvMMBu66W5nDJoGJl97gBGh0xzHpUB6BJlxZ7nDKmQIEEpQ3bDDjJWWNjutfpbs5K6jYY0WHvl8yacTkdQmuw6i7/4ccbMlbsrJqbaOPslx5d1IdnuT1CEUS5xLgcSGJIiRtyWAo7Bne+/Bsp+47D5nD0tj0wZxiFRa2cMw60TOYdWH2LNPHD2hzGbIC49bePAGbhqdIEEr6GavS1FFNi0On5znZUaZS5ztNOxFMTtMaYHM1yVwCmRwFMf/yrDAt2eRNhmaUIXcuNV1HegoAqru2qzwtd6pvOERh2VGaHepON4xlILAOt/M5/KaGkgzgjv6LKpyuFEq55Aiplgsy3F56gt9f8RypN4kPdymj/WnqtDVxdG1OMI4r0jEmAqfbk8qnBEG3xFVJ5cR7dg+GWrfpZnJPbUUJUo/fY84XCKNbqufYMdp9sEsR3tpYK57mQwPr5UHUIkThtqOA="
install:
  - npm install -g babel-eslint faucet eslint eslint-config-js
  - npm install
